### ISSUE TITLE
Issues with stern / kubectl log {pod} -f

### ISSUE THREAD

**Issue by torhagl** [jetstack/kube-oidc-proxy#122]
It seems that logging with the follow flag doesn't work. If I use stern it's not able to match any pods either.

Setup:
AKS cluster. K8s version 1.14.8.
Cert manager for TLS certificates.
NGINX for ingress.
kube-oidc-proxy deployed from the helm chart within this repo.

Expected behaviour:
![image](https://user-images.githubusercontent.com/26787631/72883442-96f4a380-3d04-11ea-9572-bcf510c8a794.png)

Actual behaviour:
![image](https://user-images.githubusercontent.com/26787631/72883499-b095eb00-3d04-11ea-9c42-c712bc06c924.png)

Please let me know if you need more information regarding this issue. :) 

Forgot to add my role / rolebinding as well:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: log-reader
  namespace: oidc-proxy
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["get", "list", "watch", "create"]
```

And the rolebinding:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-log-binding
  namespace: oidc-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: log-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: torh@stacc.com
```

**Comment by torhagl** [comment]
Closing this issue as it was a permissions issue, not an issue with the project. Solved using these permissions:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-ns-superadmin
  namespace: test-ns
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs: 
    - "*"
```

Will have to dig deeper to figure out exactly which permissions are needed for this case.
