### ISSUE TITLE
Kube-OIDC-Proxy 404 error on EKS cluster using Istio

### ISSUE THREAD

**Issue by widdix123** [jetstack/kube-oidc-proxy#155]
I get this error when i run a curl command on kube-oidc-proxy url deployed on istio. 

The certs are generated by cert-manager and the URL for  kube-oidc-proxy is hosted on Istio Ingress Gateway instead of Load Balancer 

**Pods running on kube-oidc-proxy**

NAME                               READY   STATUS    RESTARTS   AGE
kube-oidc-proxy-6ddf69485b-phln4   2/2     Running   0          41m

**$ kubectl logs kube-oidc-proxy-6ddf69485b-phln4 -n kube-oidc-proxy -c kube-oidc-proxy**

_I0608 13:25:16.526357       1 secure_serving.go:178] Serving securely on [::]:443
I0608 13:25:39.737367       1 probe.go:69] OIDC provider initialized, proxy ready_

$ curl https://oidc.v4.xxxxx.com -v

> *   Trying 18.211.247.153...
> * TCP_NODELAY set
> * Connected to oidc.v4.xxxxxx.com (xxxxxxx) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /etc/ssl/cert.pem
>   CApath: none
> * TLSv1.2 (OUT), TLS handshake, Client hello (1):
> * TLSv1.2 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
> * ALPN, server accepted to use h2
> * Server certificate:
> *  subject: CN=oidc.v4.xxxxxx.com
> *  start date: Jun  8 06:50:47 2020 GMT
> *  expire date: Sep  6 06:50:47 2020 GMT
> *  subjectAltName: host "oidc.v4.xxxxxx.com" matched cert's "oidc.v4.xxxxxx.com"
> *  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
> *  SSL certificate verify ok.
> * Using HTTP2, server supports multi-use
> * Connection state changed (HTTP/2 confirmed)
> * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> * Using Stream ID: 1 (easy handle 0x7fa04680a400)
> > GET / HTTP/2
> > Host: oidc.v4.xxxxxx.com
> > User-Agent: curl/7.64.1
> > Accept: */*
> >
> * Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
> < HTTP/2 404
> < date: Mon, 08 Jun 2020 13:41:26 GMT
> < server: istio-envoy
> <
> * Connection #0 to host oidc.v4.fpcomplete.com left intact
> * Closing connection 0

Can someone suggest what am i do wrong ?

**Comment by widdix123** [comment]
@JoshVanL  - Any inputs we are actually stuck and the documentation does not give a clarity as to say how will kube-oidc-proxy be accessed ?

**Comment by JoshVanL** [comment]
Hi @widdix123, looking at the logs, it looks like your request isn't getting to kube-oidc-proxy at all, especially since you got a 404 rather than a 401 on a clean curl request.

I'd suggest taking a look at your routes on the istio side to make sure that's set up correctly.

**Comment by widdix123** [comment]
Thanks @JoshVanL  - Yes tls was getting terminated at the Istio IngressGateway that i managed to fix . I get now 401 as suggested

I am using Gangway to fetch the kubernetes config file and Dex to authorize the user (both running on Istio). The certificate i used is of LetsEncrypt CA for all domains and the same has been used

On running `kubectl get pods` i get the " x509: certificate signed by unknown authority" error 

```
I0609 08:34:25.389313    5204 round_trippers.go:444] Response Headers:
I0609 08:34:25.389423    5204 cached_discovery.go:121] skipped caching discovery info due to Get https://oidc.v4.xxxxx.com/api?timeout=32s: x509: certificate signed by unknown authority
```
 

The requests are reaching the pods now 
```
2020-06-09 03:04:36.501543 I | http: TLS handshake error from 127.0.0.1:47520: remote error: tls: bad certificate
2020-06-09 03:04:42.058269 I | http: TLS handshake error from 127.0.0.1:47672: remote error: tls: bad certificate
2020-06-09 03:04:47.477603 I | http: TLS handshake error from 127.0.0.1:47812: remote error: tls: bad certificate
```
Server : https://oidc.v4.xxxxx.com ( Kube OIDC Proxy URL) 

Kubeconfig genereated by gangway for user widdix@xxxx.com which has a RBAC role created in the cluster

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: ca-xxxx-v4-prod.pem
    server: https://oidc.v4.xxxxx.com
  name: xxx-v4-xxx
contexts:
- context:
    cluster: xxx-v4-xxx
    user: widdix@xxxx.com
  name: xxxx-v4-xxxx
current-context: xxx-v4-xxxx
kind: Config
preferences: {}
users:
- name: widdix123@xxxx.com
  user:
    auth-provider:
      config:
        client-id: gangway
        client-secret: xxxxxx
        id-token: xxxxxx
        idp-issuer-url: https://dex.v4.xxxxxx.com/dex
        refresh-token: xxxxxxx
      name: oidc
```

**ConfigMap of gangway**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: gangway
  namespace: gangway
data:
  gangway.yaml: |
    clusterName: "xxxx-v4-prod"
    authorizeURL: "https://dex.v4.xxxx.com/dex/auth"
    tokenURL: "https://dex.v4.xxxxx.com/dex/token"
    redirectURL: "https://gangway.v4.xxxxx.com/callback"
    scopes: ["openid", "profile", "email", "offline_access"]
    clientID: "gangway"
    clientSecret: xxxxx
    usernameClaim: "name"
    emailClaim: "email"
    apiServerURL: "https://oidc.v4.xxxx.com"
````

Can you please take a look on the kubeconfig generated by gangway and suggest ?

**Comment by widdix123** [comment]
@JoshVanL - When i use the attached pem file for letsencrypt , i now get 

```
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```
[letsencrpyt.pem.txt](https://github.com/jetstack/kube-oidc-proxy/files/4750447/letsencrpyt.pem.txt)

**Comment by JoshVanL** [comment]
@widdix123 Looks like the token is not getting sent right from the client, or the server is miss configured potentially (thought less likely the client being generated from gangway. Would you be able to share your deployment  configuration for kube-oidc-proxy?

**Comment by widdix123** [comment]
@JoshVanL - I just added one option "- `--token-passthrough`

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-oidc-proxy
  name: kube-oidc-proxy
  namespace: kube-oidc-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-oidc-proxy
  template:
    metadata:
      labels:
        app: kube-oidc-proxy
    spec:
      serviceAccountName: kube-oidc-proxy
      containers:
      - image: quay.io/jetstack/kube-oidc-proxy:v0.3.0
        ports:
        - containerPort: 443
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        name: kube-oidc-proxy
        command: ["kube-oidc-proxy"]
        args:
          - "--secure-port=443"
          - "--tls-cert-file=/etc/oidc/tls/crt.pem"
          - "--tls-private-key-file=/etc/oidc/tls/key.pem"
          - "--oidc-client-id=$(OIDC_CLIENT_ID)"
          - "--oidc-issuer-url=$(OIDC_ISSUER_URL)"
          - "--oidc-username-claim=$(OIDC_USERNAME_CLAIM)"
          - "--oidc-ca-file=/etc/oidc/oidc-ca.pem"
          - "--token-passthrough"
        env:
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: kube-oidc-proxy-config
              key: oidc.client-id
        - name: OIDC_ISSUER_URL
          valueFrom:
            secretKeyRef:
              name: kube-oidc-proxy-config
              key: oidc.issuer-url
        - name: OIDC_USERNAME_CLAIM
          valueFrom:
            secretKeyRef:
              name: kube-oidc-proxy-config
              key: oidc.username-claim
        volumeMounts:
          - name: kube-oidc-proxy-config
            mountPath: /etc/oidc
            readOnly: true
          - name: kube-oidc-proxy-tls
            mountPath: /etc/oidc/tls
            readOnly: true
      volumes:
        - name: kube-oidc-proxy-config
          secret:
            secretName: kube-oidc-proxy-config
            items:
            - key: oidc.ca-pem
              path: oidc-ca.pem
        - name: kube-oidc-proxy-tls
          secret:
            secretName: kube-oidc-proxy-tls
            items:
            - key: tls.crt
              path: crt.pem
            - key: tls.key
              path: key.pem
```
