### ISSUE TITLE
Unable to connect to the server: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by agill17** [jetstack/kube-oidc-proxy#160]
Hi there, I am attempting to use this project along with dex + dex-k8s-authenticator on EKS. Whenever I run any kubectl commands I get the following error: `Unable to connect to the server: x509: certificate signed by unknown authority`

Here are values override for kube-oidc-proxy
```
oidc:
   clientId: k8s-dex-authenticator
   issuerUrl: my-dex-url
   usernameClaim: email
ingress:
   enabled: true
   annotations:
     kubernetes.io/ingress.class: nginx
   hosts:
     - host: oidc.endpoint.url
       paths: 
       - /

```

kubeconfig file looks like this;
```
- cluster:
    certificate-authority: certs/dev/k8s-ca.crt
    server: https://oidc.endpoint.url
  name: dev
users:
- name: admin-dev
  user:
    auth-provider:
      config:
        client-id: k8s-dex-authenticator
        client-secret: super-secret..........
        id-token: id-token-xxxx.......
        idp-issuer-url: my-dex-url
        refresh-token: refresh-token.....
      name: oidc
contexts:
- context:
    cluster: dev
    user: admin-dev
  name: admin-dev
``` 

oidc-proxy logs
```
I0704 22:39:40.211455       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I0704 22:40:03.113429       1 probe.go:69] OIDC provider initialized, proxy ready
```

**Note: I am terminating TLS on my load balancer**

Any pointers?
